# Generated by Django 4.0.5 on 2022-06-14 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_loaner_duemoney'),
    ]

    operations = [
        migrations.CreateModel(
            name='banker',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
    ]
