# Generated by Django 4.0.5 on 2022-06-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_banker'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_banker',
            field=models.BooleanField(default=False),
        ),
    ]
